// registeredPatients
POST http://localhost:3001/registeredPatientsSummary
Content-Type: application/json

{
  "facilityCode": 2,
  "level": 5,
  "month": "November",
  "year": 2021,
  "totalRegisteredPatients": 1000,
  "dataSummary": {
    "male": 600,
    "female": 1400,
    "ageGroups": {
      "0-4": 50,
      "5-14": 100,
      "15-24": 100,
      "25-34": 100,
      "35-44": 150,
      "45-54": 75,
      "55-64": 200,
      "65-74": 60,
      "75-84": 100,
      "85-94": 40,
      "95-104": 20,
      "105 and over": 5
    }
  }
}

###
GET http://localhost:3001/registeredPatientsSummary

###

GET http://localhost:3001/registeredPatientsSummary/1

###
GET http://localhost:3001/registeredPatientsSummary/category/aggregate

###
GET http://localhost:3001/healthFacility/registeredPatientsSummary/November-2021

###
// healthFacility
POST  http://localhost:3001/healthFacility
Content-Type: application/json

{
  "facilityName": "Kinangop",
  "facilityId": 4,
  "county": "Nairobi",
  "level": 4
}

###
GET http://localhost:3001/healthFacility/1


###
GET http://localhost:3001/healthFacility

###
GET http://localhost:3001/healthFacility/submissions
